In [ ]:
import cv2
import numpy as np
img = cv2.imread('kongfu-panda.jpg',1)
cv2.imshow('src',img)
imginfo=img.shape
height=imginfo[0]
width=imginfo[1]
deep=imginfo[2]
newimginfo=(height,width*2,deep)
dst=np.zeros(newimginfo,np.uint8)
print(dst)
for i in range(0,height):
    for j in range(0,width):
        dst[i,j]=img[i,j]
        dst[i,width*2-j-1]=img[i,j]
for j in range(0,height):
    dst[j,width]=(255,255,255)
cv2.imshow('dst',dst)
cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
